//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShare.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Español {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Español() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportShare.Idiomas.Español", typeof(Español).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atletismo.
        /// </summary>
        internal static string btnAtletismoBuscar {
            get {
                return ResourceManager.GetString("btnAtletismoBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baloncesto.
        /// </summary>
        internal static string btnBaloncestoBuscar {
            get {
                return ResourceManager.GetString("btnBaloncestoBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        internal static string btnCerrarSesion {
            get {
                return ResourceManager.GetString("btnCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciclismo.
        /// </summary>
        internal static string btnCiclismoBuscar {
            get {
                return ResourceManager.GetString("btnCiclismoBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Futbol.
        /// </summary>
        internal static string btnFutbolBuscar {
            get {
                return ResourceManager.GetString("btnFutbolBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tenis.
        /// </summary>
        internal static string btnTenisBuscar {
            get {
                return ResourceManager.GetString("btnTenisBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Celebración Evento:.
        /// </summary>
        internal static string grpboxDatosCelebracionCrear {
            get {
                return ResourceManager.GetString("grpboxDatosCelebracionCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requisitos a cumplir por participantes:.
        /// </summary>
        internal static string grpboxRequisitosCrear {
            get {
                return ResourceManager.GetString("grpboxRequisitosCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deporte:.
        /// </summary>
        internal static string lblDeporteCrear {
            get {
                return ResourceManager.GetString("lblDeporteCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del Evento:.
        /// </summary>
        internal static string lblDescripcionEventoCrear {
            get {
                return ResourceManager.GetString("lblDescripcionEventoCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destacados.
        /// </summary>
        internal static string lblDestacadosBuscar {
            get {
                return ResourceManager.GetString("lblDestacadosBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día:.
        /// </summary>
        internal static string lblDiaCrear {
            get {
                return ResourceManager.GetString("lblDiaCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad:.
        /// </summary>
        internal static string lblEdadCrear {
            get {
                return ResourceManager.GetString("lblEdadCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora:.
        /// </summary>
        internal static string lblHoraCrear {
            get {
                return ResourceManager.GetString("lblHoraCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localización:.
        /// </summary>
        internal static string lblLocalizacionCrear {
            get {
                return ResourceManager.GetString("lblLocalizacionCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel Deportivo:.
        /// </summary>
        internal static string lblNivelDeportivoCrear {
            get {
                return ResourceManager.GetString("lblNivelDeportivoCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Evento:.
        /// </summary>
        internal static string lblNombreEventoCrear {
            get {
                return ResourceManager.GetString("lblNombreEventoCrear", resourceCulture);
            }
        }
    }
}
